# Generated by Django 4.1.1 on 2022-09-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('articles', '0001_initial'), ('articles', '0002_rename_articles_ar_status_edb746_idx_article_status')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[(0, 'Удалено'), (1, 'Черновик'), (2, 'Опубликовано')], default=1, max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status'], name='articles_ar_status_edb746_idx'),
        ),
        migrations.RenameIndex(
            model_name='article',
            new_name='article_status',
            old_name='articles_ar_status_edb746_idx',
        ),
    ]
